### ISSUE TITLE
Ensembl Upgrade to Rat Assembly mRatBN7.2 Breaks Export

### ISSUE THREAD

**Issue by ACastanza** [related-sciences/ensembl-genes#12]
Ensembl 105 updated the rat genome assembly from Rnor_6.0 to mRatBN7.2. This causes the export to fail:
https://github.com/ACastanza/ensembl-genes/runs/4481560669?check_suite_focus=true

**Comment by dhimmel** [comment]
Thanks! So the new database is `rattus_norvegicus_core_105_72`.

**Comment by dhimmel** [comment]
Also noting the [ensembl 105 release notes](https://www.ensembl.info/2021/12/10/ensembl-105-has-been-released/) which include:

> Rat (Rattus norvegicus) has been updated from Rnor 6.0 to mRatBN7.1

But perhaps `mRatBN7.1` is a typo and should be `mRatBN7.2`?

**Comment by dhimmel** [comment]
Running an ensembl 105 export in https://github.com/related-sciences/ensembl-genes/actions/runs/1564168231

**Comment by ACastanza** [comment]
RGD is also saying 7.2 (https://rgd.mcw.edu/wg/news/new-rat-genome/) so I assume it's just a typo in their release notes
