### ISSUE TITLE
Support species besides human?

### ISSUE THREAD

**Issue by dhimmel** [related-sciences/ensembl-genes#4]
@ACastanza [asked](https://twitter.com/ACastanza/status/1447995125645283329):

> Versions for Mouse and Rat as well?

We should think about support for additional species, since it appears there will at least be demand for it.

**Comment by dhimmel** [comment]
There are at least two places where humanity is assumed:

https://github.com/related-sciences/ensembl-genes/blob/627b2641efb494575e88a9912ee4ae39947e2341/src/ensembl_genes.py#L43

https://github.com/related-sciences/ensembl-genes/blob/627b2641efb494575e88a9912ee4ae39947e2341/src/ensembl_genes.py#L97-L98

**Comment by dhimmel** [comment]
Have made lot's of progress here such that we can configure the species.

One remaining task is to switch to output branches that include species. I am thinking from changing the output branches from `output-104` to `output_homo_sapiens_core_104_38` such that they include the full database name. This will lead to URLs that are a bit longer and more unwieldy but will better match the design that each export corresponds to a single core database.

Another option would be to have multiple directories under each release for different species. This would result in less branches but would require exporting all species at once, which doesn't seem ideal.

**Comment by ACastanza** [comment]
I would lean towards folders. It would keep releases together better and In my use-case (which is admittedly not the typical one) I'd want to take the information from all species for a given release.

I think calling the other databases would need their own set of special purpose scripts.

**Comment by dhimmel** [comment]
> I'm sure that someone would find annotations for current genes on the old assembly useful

Thanks for the explanation. It seems likely that we might want to support multiple assemblies per release especially during transitional periods, even if that deprives us the satisfaction of forcing others to upgrade 😏 . Therefore, I'm inclined to use the database name like `homo_sapiens_core_104_38` as either the species directory or branch name (depending on how we proceed). This would require users to explicitly choose the assembly when selecting a branch/directory and is probably good for awareness that some fields are assembly specific.

> Separate branches for each species for each release would be a huge mess if expanding this to any particularly large selection of the available species

Worst case scenario, we support all 310 species and there are 4 releases per year and the life of this project is a decade. Ignoring supporting multiple assemblies for the same release, we'd have 12400 branches.

https://github.com/flutter/flutter has 265 branches and the github interface is quite nice for filtering branches by substring match.

I imagine at some point we'll hit limits, but not due to the number of branches but instead cumulative file size in the repo. We can start deploying these branches to new repos, perhaps one repo per release or release year. Or we might switch to another storage solution.

One challenge with directories is that users who only want a single species, might have to download all species. Git's `sparseCheckout` is one workaround but looks a bit technical for many users.

With the branch method, a shell script like the following would get all three directories you'd like next to each other in a local directory.

```shell
release=104
databases=( homo_sapiens_core_${release}_38 mus_musculus_core_${release}_39 rattus_norvegicus_core_${release}_6 )
for database in "${databases[@]}"
do
   # remove echo to execute
   echo git clone --branch=output_$database --depth=1 https://github.com/related-sciences/ensembl-genes.git
done
```

Another challenge to directories is that the CI export jobs will take longer if they have to process multiple species. But I'm still open to this and will think about it some more. Happy to hear any additional feedback.

**Comment by dhimmel** [comment]
Looks to be working! https://github.com/related-sciences/ensembl-genes/actions/runs/1344344511

> ![image](https://user-images.githubusercontent.com/1117703/137423704-fb3ccfaf-464a-45c6-b529-febd1874c297.png)
